<?php
// database/seeders/KeyIssueSeeder.php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\KeyIssue;

class KeyIssueSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $issues = [
            [
                'title'       => 'Review FDD presentations and extract key issues',
                'description' => 'Look at the Ministry of Finance (Fiscal Decentralization Division) presentations and bring out the key issues.',
                'owner'       => 'Ministry of Finance (FDD)',
                'priority'    => 'high',
                'status'      => 'open',
                'opened_at'   => $now,
                'due_at'      => null,
                'source'      => 'IMC Key Issues',
                'tags'        => 'governance;fiscal-decentralization',
                'created_at'  => $now, 'updated_at' => $now,
            ],
            [
                'title'       => 'Identify key local council fiscal challenges',
                'description' => 'Identify and list the key fiscal challenges facing local councils.',
                'owner'       => 'Local Councils / MoF (FDD)',
                'priority'    => 'high',
                'status'      => 'open',
                'opened_at'   => $now,
                'due_at'      => null,
                'source'      => 'IMC Key Issues',
                'tags'        => 'finance;local-councils',
                'created_at'  => $now, 'updated_at' => $now,
            ],
            [
                'title'       => 'Review vertical & horizontal revenue sharing mechanisms',
                'description' => 'MoF to look into vertical and horizontal revenue sharing mechanisms.',
                'owner'       => 'Ministry of Finance',
                'priority'    => 'high',
                'status'      => 'open',
                'opened_at'   => $now,
                'due_at'      => null,
                'source'      => 'IMC Key Issues',
                'tags'        => 'revenue-sharing;policy',
                'created_at'  => $now, 'updated_at' => $now,
            ],
            [
                'title'       => 'Set up inter-agency working group',
                'description' => 'Working group actions: MoPED, MoF, Deputy Mayor of FCC, LC Reps, FDD, DECSEC.',
                'owner'       => 'MoPED / MoF / FCC / LCs / FDD / DECSEC',
                'priority'    => 'medium',
                'status'      => 'open',
                'opened_at'   => $now,
                'due_at'      => null,
                'source'      => 'IMC Key Issues',
                'tags'        => 'coordination;working-group',
                'created_at'  => $now, 'updated_at' => $now,
            ],
            [
                'title'       => 'Increase stakeholder engagement & collaborative decision-making',
                'description' => 'Increase engagement and make collaborative decisions with stakeholders.',
                'owner'       => 'All Stakeholders',
                'priority'    => 'medium',
                'status'      => 'open',
                'opened_at'   => $now,
                'due_at'      => null,
                'source'      => 'IMC Key Issues',
                'tags'        => 'engagement;collaboration',
                'created_at'  => $now, 'updated_at' => $now,
            ],
            [
                'title'       => 'Develop positive solutions to mitigate LC challenges',
                'description' => 'Seek positive solutions that mitigate local council challenges.',
                'owner'       => 'Local Councils / Line Ministries',
                'priority'    => 'medium',
                'status'      => 'open',
                'opened_at'   => $now,
                'due_at'      => null,
                'source'      => 'IMC Key Issues',
                'tags'        => 'problem-solving;local-councils',
                'created_at'  => $now, 'updated_at' => $now,
            ],
            [
                'title'       => 'Strengthen CA–political head collaboration',
                'description' => 'Chief Administrators to build collaborative working relationships with political heads.',
                'owner'       => 'Chief Administrators',
                'priority'    => 'medium',
                'status'      => 'open',
                'opened_at'   => $now,
                'due_at'      => null,
                'source'      => 'IMC Key Issues',
                'tags'        => 'governance;leadership',
                'created_at'  => $now, 'updated_at' => $now,
            ],
            [
                'title'       => 'Hold inter-council staff transfers pending audit',
                'description' => 'Place a hold on inter-council staff transfers until a proper audit is conducted.',
                'owner'       => 'Local Councils / HR',
                'priority'    => 'high',
                'status'      => 'open',
                'opened_at'   => $now,
                'due_at'      => null,
                'source'      => 'IMC Key Issues',
                'tags'        => 'hr;audit;transfers',
                'created_at'  => $now, 'updated_at' => $now,
            ],
            [
                'title'       => 'Support LC capital investment',
                'description' => 'MoF to aid Local Councils in capital investment.',
                'owner'       => 'Ministry of Finance',
                'priority'    => 'high',
                'status'      => 'open',
                'opened_at'   => $now,
                'due_at'      => null,
                'source'      => 'IMC Key Issues',
                'tags'        => 'capital-investment;finance',
                'created_at'  => $now, 'updated_at' => $now,
            ],
            [
                'title'       => 'Procure 25 council vehicles (with MoT request)',
                'description' => 'MoF will procure 25 council vehicles to enhance operations; Ministry of Transport to make official request.',
                'owner'       => 'MoF / Ministry of Transport',
                'priority'    => 'medium',
                'status'      => 'open',
                'opened_at'   => $now,
                'due_at'      => null,
                'source'      => 'IMC Key Issues',
                'tags'        => 'assets;transport;operations',
                'created_at'  => $now, 'updated_at' => $now,
            ],
            [
                'title'       => 'Establish collateral framework for LC borrowing',
                'description' => 'Set collateral to aid local council borrowing.',
                'owner'       => 'MoF / Central Government',
                'priority'    => 'medium',
                'status'      => 'open',
                'opened_at'   => $now,
                'due_at'      => null,
                'source'      => 'IMC Key Issues',
                'tags'        => 'borrowing;policy;finance',
                'created_at'  => $now, 'updated_at' => $now,
            ],
            [
                'title'       => 'Increase local taxes based on local contexts',
                'description' => 'Increase local taxes nationwide according to distinctive local settings.',
                'owner'       => 'Local Councils / MoF',
                'priority'    => 'medium',
                'status'      => 'open',
                'opened_at'   => $now,
                'due_at'      => null,
                'source'      => 'IMC Key Issues',
                'tags'        => 'taxation;local-revenue',
                'created_at'  => $now, 'updated_at' => $now,
            ],
            [
                'title'       => 'Clarify and implement property tax policy',
                'description' => 'State and implement property tax approach.',
                'owner'       => 'Local Councils / MoF',
                'priority'    => 'medium',
                'status'      => 'open',
                'opened_at'   => $now,
                'due_at'      => null,
                'source'      => 'IMC Key Issues',
                'tags'        => 'property-tax;revenue',
                'created_at'  => $now, 'updated_at' => $now,
            ],
            [
                'title'       => 'Set realistic deadlines for deliverables',
                'description' => 'Set realistic deadlines for all deliverables.',
                'owner'       => 'All Implementing Partners',
                'priority'    => 'low',
                'status'      => 'open',
                'opened_at'   => $now,
                'due_at'      => null,
                'source'      => 'IMC Key Issues',
                'tags'        => 'planning;pm',
                'created_at'  => $now, 'updated_at' => $now,
            ],
            [
                'title'       => 'Strengthen joint working culture',
                'description' => 'Work together to achieve the desired objective.',
                'owner'       => 'All Stakeholders',
                'priority'    => 'low',
                'status'      => 'open',
                'opened_at'   => $now,
                'due_at'      => null,
                'source'      => 'IMC Key Issues',
                'tags'        => 'collaboration;culture',
                'created_at'  => $now, 'updated_at' => $now,
            ],
            [
                'title'       => 'Coordinate MoE & LCs on school buses',
                'description' => 'Ministry of Education to work collaboratively with Local Councils on running school buses.',
                'owner'       => 'Ministry of Education / Local Councils',
                'priority'    => 'medium',
                'status'      => 'open',
                'opened_at'   => $now,
                'due_at'      => null,
                'source'      => 'IMC Key Issues',
                'tags'        => 'education;transport;service-delivery',
                'created_at'  => $now, 'updated_at' => $now,
            ],
            [
                'title'       => 'Recruit roving core staff',
                'description' => 'Recruit roving core staff to step in during transfers, resignations and dismissals.',
                'owner'       => 'Local Councils / HRMO',
                'priority'    => 'medium',
                'status'      => 'open',
                'opened_at'   => $now,
                'due_at'      => null,
                'source'      => 'IMC Key Issues',
                'tags'        => 'hr;capacity',
                'created_at'  => $now, 'updated_at' => $now,
            ],
            [
                'title'       => 'Review NRA role in income tax collection',
                'description' => 'Government to look into the National Revenue Authority’s involvement in collecting income taxes.',
                'owner'       => 'Government / NRA / MoF',
                'priority'    => 'medium',
                'status'      => 'open',
                'opened_at'   => $now,
                'due_at'      => null,
                'source'      => 'IMC Key Issues',
                'tags'        => 'tax-administration;policy',
                'created_at'  => $now, 'updated_at' => $now,
            ],
            [
                'title'       => 'Create effective central–local coordination mechanism',
                'description' => 'Create an effective coordinating mechanism between central government, councils and other stakeholders for service delivery.',
                'owner'       => 'Government / Local Councils',
                'priority'    => 'high',
                'status'      => 'open',
                'opened_at'   => $now,
                'due_at'      => null,
                'source'      => 'IMC Key Issues',
                'tags'        => 'coordination;service-delivery;governance',
                'created_at'  => $now, 'updated_at' => $now,
            ],
            [
                'title'       => 'Construct new LC office structures',
                'description' => 'Construct new office structures for Port Loko City, Karene and Falaba District Councils.',
                'owner'       => 'Government / MWHI',
                'priority'    => 'medium',
                'status'      => 'open',
                'opened_at'   => $now,
                'due_at'      => null,
                'source'      => 'IMC Key Issues',
                'tags'        => 'infrastructure;facilities',
                'created_at'  => $now, 'updated_at' => $now,
            ],
            [
                'title'       => 'Assess challenges facing devolution',
                'description' => 'Review the challenges facing devolution.',
                'owner'       => 'Line Ministries / Local Government',
                'priority'    => 'high',
                'status'      => 'open',
                'opened_at'   => $now,
                'due_at'      => null,
                'source'      => 'IMC Key Issues',
                'tags'        => 'devolution;assessment',
                'created_at'  => $now, 'updated_at' => $now,
            ],
            [
                'title'       => 'Complete devolution of finances, personnel & functions',
                'description' => 'Ministries to complete devolution of finances, personnel and functions.',
                'owner'       => 'Line Ministries',
                'priority'    => 'high',
                'status'      => 'open',
                'opened_at'   => $now,
                'due_at'      => null,
                'source'      => 'IMC Key Issues',
                'tags'        => 'devolution;reform;hr;finance',
                'created_at'  => $now, 'updated_at' => $now,
            ],
            [
                'title'       => 'Engage mining companies on royalty payments',
                'description' => 'Government to engage mining companies on payment of royalties to chiefdom administration.',
                'owner'       => 'Government / Mining Companies',
                'priority'    => 'medium',
                'status'      => 'open',
                'opened_at'   => $now,
                'due_at'      => null,
                'source'      => 'IMC Key Issues',
                'tags'        => 'mining;royalties;chiefdoms',
                'created_at'  => $now, 'updated_at' => $now,
            ],
        ];

        // Upsert by title so running the seeder twice won’t duplicate.
        KeyIssue::upsert(
            $issues,
            ['title'],
            ['description','owner','priority','status','opened_at','due_at','source','tags','updated_at']
        );
    }
}
